server:
  port: 9021
  servlet:
    context-path: /
spring:
  application:
    name: sc-producer
  database:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
eureka:
  client:
    server-url:
      defaultZone: http://localhost:9001/eureka/
